apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerClass: io.cilium/lbi-pam
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
  selector:
    app: mosquitto