apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto
  sessionAffinity: None
  type: LoadBalancer