apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pull in everything from base, then apply our overrides below.
resources:
  - ../../base

# All resources in this overlay get this namespace.
namespace: pixelclock-dev

patches:
  - path: patch-service.yaml
