apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pixelclock-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Sync after MQTT app
spec:
  project: default
  source:
    repoURL: git@github.com:rosej904/pixelclock.git
    targetRevision: HEAD
    path: k8s/pixelclock/overlays/dev # ArgoCD automatically detects Kustomize here
  destination:
    server: https://kubernetes.default.svc
    namespace: pixelclock-dev